name: Benchmarks
on:
  push:
    branches: [ "main" ]
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: ./build.sh
    - name: Run test suite
      run: ./bin/kiwi tests/test
    - name: Run benchmarks
      run: ./bin/kiwi examples/data/heavy_pipeline.kiwi
